- menu_name: "Link"

- name: "Shenyang Institute of Automation, Chinese Academy of Sciences"
  url: "http://www.sia.cas.cn/"

- name: "State Key Laboratory of Robotics, SIA"
  url: "http://www.sia.cas.cn/jgsz/kyxt/jqrxyjs/"

- name: "Author: Jiwei Li"
  url: "https://github.com/k2muse"
